//////////////////////////////////////////////////////////////////////////
// @author Sidorenko "PC" Alexander
// @date 03.07.2006
// email: sidorenko.alexander@gmail.com
// project: RGDE
// description: 
// example of use:
//////////////////////////////////////////////////////////////////////////

#pragma once

const std::string FileHeader = 
std::string("/********************************************************\n") + 
std::string(" * This file is generated by RGDE EffectGenerator.      *\n") +
std::string(" * (c) RGDE Team. 2006.                                 *\n") +
std::string(" ********************************************************/\n\n\n");

const std::string IncludeAllConstantName = "IncludeAllFile";
const std::string IncludeAllDefaultValue = "All.fx";

const std::string ForceIncludeConstantName = "ForceInclude";